services:
  - type: web
    name: testpilot-backend
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    postBuildCommand: playwright install chromium
    plan: free
